### ISSUE TITLE
'Can only add notification blocks from within runloops.'

### ISSUE THREAD

**Issue by MikeGarcia** [bigfish24/ABFRealmGridController#1]
Running the demo thats provided, I am getting a 'Can only add notification blocks from within runloops.' RLMException. This is happening on Realm 0.97.0, everything appears to be working fine on versions < 0.97.0.

**Comment by bigfish24** [comment]
Yes this is actually an issue that needs to be addressed in: https://github.com/Roobiq/RBQFetchedResultsController

Right now it is possible that `RBQFetchedResultsController` will attempt to add a notification block on a thread without a run loop. This is occurring with `ABFRealmGridController` because the network response for the NYT stories is being processed on a thread without a runloop.

I will work to fix this issue which you can track here: https://github.com/Roobiq/RBQFetchedResultsController/issues/52

**Comment by bigfish24** [comment]
This is now fixed as of v2.6 of RBQFetchedResultsController: https://github.com/Roobiq/RBQFetchedResultsController/commit/ba8c5595e48e9f6a50638f3f33a9a986e48b9c41

Run `pod update` to get the latest.

**Comment by harmoniqpunk** [comment]
I encounter this problem on RealmSwift 0.99.1 by creating multiple notification tokens instances inside a loop.

**Comment by bigfish24** [comment]
Hmm I need to update this library to remove RBFRC which will solve this, since realm support fine grained notifications now directly

**Comment by gagarwal** [comment]
I am facing the same issues with 0.99.1.
